### ISSUE TITLE
App can't be enabled

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [hurradieweltgehtunter/oc_landbot#1]
![image](https://user-images.githubusercontent.com/16665512/57611632-9ac80780-7573-11e9-97b5-7d10f7b4426f.png)

# Steps to reproduce
1. Clone repo to /apps/
2. Click on "enable" in the app administration panel

I used the xmas app by Tom Needham (https://github.com/tomneedham/oc_xmas) as a template and changed the namespace, id etc. Maybe I did sth wrong?

**Comment by DeepDiver1975** [comment]
max version 10.0 - https://github.com/hurradieweltgehtunter/oc_landbot/blob/68c3786256bc24cb5a584f9c01dcd2d47d08a29a/appinfo/info.xml#L13

might be related

**Comment by hurradieweltgehtunter** [comment]
changed to max-version=12 but still not working

**Comment by hurradieweltgehtunter** [comment]
solved it. app folder name was wrong
